version: '3'

services:
  client:
    build: ../joboonja-front
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
    links:
      - server
    depends_on:
      - server
    networks:
      joboonjanet
  server:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - db
    networks:
      joboonjanet
  db:
    image: mysql
    restart: always
    container_name: db
    environment:
      - MYSQL_DATABASE=joboonja
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
    ports:
      - 3306:3306
    volumes:
      - ./data/db/mysql:/var/lib/mysql
    command:
    networks:
      - joboonjanet

networks:
  joboonjanet:
    driver: bridge