version: '3'

services:
  client:
    build: ./joboonja-front/
    ports:
      - "3000:80"
    depends_on:
      - server
  server:
    build: .
    restart: always
    ports:
      - "8000:8080"
    environment:
      WAIT_HOSTS: db:3306
    depends_on:
      - db
    tty: true
  db:
    image: mysql
    restart: always
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - ./database/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 3s
      retries: 10