version: '3'

services:
  client:
    build: ./joboonja-front/
    ports:
      - "3000:80"
    depends_on:
      - server
  server:
    build: .
    restart: always
    ports:
      - "8000:8080"
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=joboonja
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./database/mysql:/var/lib/mysql