version: '3'

services:
  client:
    build: ../joboonja-front
    ports:
      - "3000:80"
    depends_on:
      - server
  server:
    build: .
    ports:
      - "8000:8080"
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    container_name: db
    environment:
#      - MYSQL_DATABASE=joboonja
      - MYSQL_ROOT_PASSWORD=1234
#      - MYSQL_USER=admin
#      - MYSQL_PASSWORD=1234
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - ./database/mysql:/var/lib/mysql